(cl:in-package fusion_model-msg)
(cl:export '(HEADER-VAL
          HEADER
          TYPE-VAL
          TYPE
          X1-VAL
          X1
          Y1-VAL
          Y1
          X2-VAL
          X2
          Y2-VAL
          Y2
          SCORE-VAL
          SCORE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          L-VAL
          L
          H-VAL
          H
          W-VAL
          W
          ROT_Y-VAL
          ROT_Y
          ORI_TMP-VAL
          ORI_TMP
          OBJECT_ID-VAL
          OBJECT_ID
))